[2024-11-18T01:54:00.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T01:54:00.831+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_clima_1.clean_weather_data manual__2024-11-18T01:53:53.486963+00:00 [queued]>
[2024-11-18T01:54:00.844+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_clima_1.clean_weather_data manual__2024-11-18T01:53:53.486963+00:00 [queued]>
[2024-11-18T01:54:00.846+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-18T01:54:00.874+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): clean_weather_data> on 2024-11-18 01:53:53.486963+00:00
[2024-11-18T01:54:00.888+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=964) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T01:54:00.891+0000] {standard_task_runner.py:72} INFO - Started process 966 to run task
[2024-11-18T01:54:00.892+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_clima_1', 'clean_weather_data', 'manual__2024-11-18T01:53:53.486963+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/***_clima_1.py', '--cfg-path', '/tmp/tmp7tt2twcj']
[2024-11-18T01:54:00.896+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask clean_weather_data
[2024-11-18T01:54:00.990+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_clima_1.clean_weather_data manual__2024-11-18T01:53:53.486963+00:00 [running]> on host 0fb026160db8
[2024-11-18T01:54:01.129+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_clima_1' AIRFLOW_CTX_TASK_ID='clean_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T01:53:53.486963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T01:53:53.486963+00:00'
[2024-11-18T01:54:01.131+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T01:54:01.133+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T01:54:01.134+0000] {logging_mixin.py:190} INFO - Current task name:clean_weather_data state:running start_date:2024-11-18 01:54:00.832393+00:00
[2024-11-18T01:54:01.135+0000] {logging_mixin.py:190} INFO - Dag name:***_clima_1 and current dag run status:running
[2024-11-18T01:54:01.137+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T01:54:01.183+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clima_1.py", line 98, in clean_data
    data[['name', 'datetime', 'tempmin', 'temp', 'tempmax']].to_csv(csv_buffer, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 270, in save
    self._save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 274, in _save
    self._save_header()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 279, in _save_header
    self.writer.writerow(self.encoded_labels)
TypeError: descriptor 'write' for '_io.StringIO' objects doesn't apply to a 'str' object
[2024-11-18T01:54:01.222+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-18T01:54:01.223+0000] {logging_mixin.py:190} INFO - Task start:2024-11-18 01:54:00.832393+00:00 end:2024-11-18 01:54:01.221411+00:00 duration:0.389018
[2024-11-18T01:54:01.224+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): clean_weather_data> dag:<DAG: ***_clima_1> dagrun:<DagRun ***_clima_1 @ 2024-11-18 01:53:53.486963+00:00: manual__2024-11-18T01:53:53.486963+00:00, state:running, queued_at: 2024-11-18 01:53:53.510658+00:00. externally triggered: True>
[2024-11-18T01:54:01.226+0000] {logging_mixin.py:190} INFO - Failure caused by descriptor 'write' for '_io.StringIO' objects doesn't apply to a 'str' object
[2024-11-18T01:54:01.227+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=***_clima_1, task_id=clean_weather_data, run_id=manual__2024-11-18T01:53:53.486963+00:00, execution_date=20241118T015353, start_date=20241118T015400, end_date=20241118T015401
[2024-11-18T01:54:01.253+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T01:54:01.255+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task clean_weather_data (descriptor 'write' for '_io.StringIO' objects doesn't apply to a 'str' object; 966)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clima_1.py", line 98, in clean_data
    data[['name', 'datetime', 'tempmin', 'temp', 'tempmax']].to_csv(csv_buffer, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 270, in save
    self._save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 274, in _save
    self._save_header()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 279, in _save_header
    self.writer.writerow(self.encoded_labels)
TypeError: descriptor 'write' for '_io.StringIO' objects doesn't apply to a 'str' object
[2024-11-18T01:54:01.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-18T01:54:01.335+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T01:54:01.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
