[2024-11-18T01:51:43.682+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T01:51:43.700+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_clima_1.clean_weather_data manual__2024-11-18T01:51:36.406381+00:00 [queued]>
[2024-11-18T01:51:43.710+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_clima_1.clean_weather_data manual__2024-11-18T01:51:36.406381+00:00 [queued]>
[2024-11-18T01:51:43.711+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-18T01:51:43.730+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): clean_weather_data> on 2024-11-18 01:51:36.406381+00:00
[2024-11-18T01:51:43.741+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=912) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T01:51:43.744+0000] {standard_task_runner.py:72} INFO - Started process 914 to run task
[2024-11-18T01:51:43.744+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_clima_1', 'clean_weather_data', 'manual__2024-11-18T01:51:36.406381+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/***_clima_1.py', '--cfg-path', '/tmp/tmpgcdgt1d2']
[2024-11-18T01:51:43.746+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask clean_weather_data
[2024-11-18T01:51:43.821+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_clima_1.clean_weather_data manual__2024-11-18T01:51:36.406381+00:00 [running]> on host 0fb026160db8
[2024-11-18T01:51:43.996+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_clima_1' AIRFLOW_CTX_TASK_ID='clean_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T01:51:36.406381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T01:51:36.406381+00:00'
[2024-11-18T01:51:43.999+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T01:51:44.000+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T01:51:44.002+0000] {logging_mixin.py:190} INFO - Current task name:clean_weather_data state:running start_date:2024-11-18 01:51:43.701813+00:00
[2024-11-18T01:51:44.003+0000] {logging_mixin.py:190} INFO - Dag name:***_clima_1 and current dag run status:running
[2024-11-18T01:51:44.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T01:51:44.030+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clima_1.py", line 91, in clean_data
    data = pd.read_csv(read_file['body'],  sep = ',')
                       ~~~~~~~~~^^^^^^^^
KeyError: 'body'
[2024-11-18T01:51:44.058+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-18T01:51:44.059+0000] {logging_mixin.py:190} INFO - Task start:2024-11-18 01:51:43.701813+00:00 end:2024-11-18 01:51:44.057260+00:00 duration:0.355447
[2024-11-18T01:51:44.060+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): clean_weather_data> dag:<DAG: ***_clima_1> dagrun:<DagRun ***_clima_1 @ 2024-11-18 01:51:36.406381+00:00: manual__2024-11-18T01:51:36.406381+00:00, state:running, queued_at: 2024-11-18 01:51:36.425613+00:00. externally triggered: True>
[2024-11-18T01:51:44.062+0000] {logging_mixin.py:190} INFO - Failure caused by 'body'
[2024-11-18T01:51:44.063+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=***_clima_1, task_id=clean_weather_data, run_id=manual__2024-11-18T01:51:36.406381+00:00, execution_date=20241118T015136, start_date=20241118T015143, end_date=20241118T015144
[2024-11-18T01:51:44.084+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T01:51:44.086+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task clean_weather_data ('body'; 914)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clima_1.py", line 91, in clean_data
    data = pd.read_csv(read_file['body'],  sep = ',')
                       ~~~~~~~~~^^^^^^^^
KeyError: 'body'
[2024-11-18T01:51:44.122+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-18T01:51:44.149+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T01:51:44.156+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
