[2024-11-11T01:04:21.368+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T01:04:21.379+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_clima_1.get_weather_data manual__2024-11-11T01:04:19.631997+00:00 [queued]>
[2024-11-11T01:04:21.385+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_clima_1.get_weather_data manual__2024-11-11T01:04:19.631997+00:00 [queued]>
[2024-11-11T01:04:21.386+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-11T01:04:21.397+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-11-11 01:04:19.631997+00:00
[2024-11-11T01:04:21.403+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=552) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T01:04:21.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_clima_1', 'get_weather_data', 'manual__2024-11-11T01:04:19.631997+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/***_clima_1.py', '--cfg-path', '/tmp/tmpqma1f83q']
[2024-11-11T01:04:21.404+0000] {standard_task_runner.py:72} INFO - Started process 561 to run task
[2024-11-11T01:04:21.405+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask get_weather_data
[2024-11-11T01:04:21.441+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_clima_1.get_weather_data manual__2024-11-11T01:04:19.631997+00:00 [running]> on host 200931e54d9b
[2024-11-11T01:04:21.500+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_clima_1' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T01:04:19.631997+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T01:04:19.631997+00:00'
[2024-11-11T01:04:21.502+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-11T01:04:21.503+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-11T01:04:21.503+0000] {logging_mixin.py:190} INFO - Current task name:get_weather_data state:running start_date:2024-11-11 01:04:21.380664+00:00
[2024-11-11T01:04:21.504+0000] {logging_mixin.py:190} INFO - Dag name:***_clima_1 and current dag run status:running
[2024-11-11T01:04:21.505+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-11T01:04:21.506+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: extract_data() missing 1 required positional argument: 'data_interval_and'
[2024-11-11T01:04:21.513+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-11T01:04:21.514+0000] {logging_mixin.py:190} INFO - Task start:2024-11-11 01:04:21.380664+00:00 end:2024-11-11 01:04:21.513018+00:00 duration:0.132354
[2024-11-11T01:04:21.515+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_weather_data> dag:<DAG: ***_clima_1> dagrun:<DagRun ***_clima_1 @ 2024-11-11 01:04:19.631997+00:00: manual__2024-11-11T01:04:19.631997+00:00, state:running, queued_at: 2024-11-11 01:04:19.639193+00:00. externally triggered: True>
[2024-11-11T01:04:21.515+0000] {logging_mixin.py:190} INFO - Failure caused by extract_data() missing 1 required positional argument: 'data_interval_and'
[2024-11-11T01:04:21.516+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=***_clima_1, task_id=get_weather_data, run_id=manual__2024-11-11T01:04:19.631997+00:00, execution_date=20241111T010419, start_date=20241111T010421, end_date=20241111T010421
[2024-11-11T01:04:21.526+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-11T01:04:21.527+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task get_weather_data (extract_data() missing 1 required positional argument: 'data_interval_and'; 561)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: extract_data() missing 1 required positional argument: 'data_interval_and'
[2024-11-11T01:04:21.540+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-11T01:04:21.547+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
